### ISSUE TITLE
src/api_manager:config_manager_test is flaky with -c opt

### ISSUE THREAD

**Issue by lizan** [cloudendpoints/esp#219] opened 2017-07-18 00:19 UTC
```
bazel test -c opt //contrib/endpoints/src/api_manager:config_manager_test --runs_per_test=100
```
In istio/proxy repo or after #216 

```
bazel test -c opt //contrib/src/api_manager:config_manager_test --runs_per_test=100
```

will result

```
INFO: Elapsed time: 67.781s, Critical Path: 9.71s
//contrib/endpoints/src/api_manager:config_manager_test                  FAILED in 20 out of 100 in 0.2s
```

The test is temporarily disabled in #216.

**Comment by qiwzhang** [comment] 2017-07-18 01:36
@mangchiandjjoe   could you fix this test?

According to Lizan,  most likely the order is random in here

https://github.com/cloudendpoints/esp/blob/master/src/api_manager/config_manager_test.cc#L341

and 

https://github.com/cloudendpoints/esp/blob/master/src/api_manager/config_manager_test.cc#L348

since the the order of protobuf_map is undefined, and the test is asserting the order.

**Comment by mangchiandjjoe** [comment] 2017-07-18 17:57
The failure was caused by parallel http requests from config_manager to service management api service.

Created the PR(https://github.com/cloudendpoints/esp/pull/221)

**Comment by mangchiandjjoe** [comment] 2017-07-18 21:57
PR was merged.

$ bazel test -c opt //src/api_manager:config_manager_test --runs_per_test=100
INFO: Found 1 test target...
Target //src/api_manager:config_manager_test up-to-date:
  bazel-bin/src/api_manager/config_manager_test
INFO: Elapsed time: 1.490s, Critical Path: 0.14s
//src/api_manager:config_manager_test                                    PASSED in 0.1s
  Stats over 100 runs: max = 0.1s, min = 0.1s, avg = 0.1s, dev = 0.0s

Executed 1 out of 1 test: 1 test passes.

**Closed by mangchiandjjoe** 2017-07-18 21:57 UTC
