### ISSUE TITLE
Valid JWT rejected with BAD_FORMAT

### ISSUE THREAD

**Issue by tazjin** [cloudendpoints/esp#308] opened 2017-11-10 15:20 UTC
When sending a request to a Cloud Endpoints deployment with a JWT generated by [Keycloak](https://www.keycloak.org/) we struggle with the following error message:

```json
{
  "code": 16,
  "message": "JWT validation failed: BAD_FORMAT",
  "details": [
    {
      "@type": "type.googleapis.com/google.rpc.DebugInfo",
      "stackEntries": [],
      "detail": "auth"
    }
  ]
}
```

We've gone through the [JWT troubleshooting](https://cloud.google.com/endpoints/docs/openapi/troubleshoot-jwt-openapi) document and tried everything we could think of, short of recompiling the ESP with a bunch of debug log statements to figure out [where in this method](https://github.com/grpc/grpc/blob/a5ddf26c3386031b2485784199160d107b972991/src/core/lib/security/credentials/jwt/jwt_verifier.cc#L246) it fails.

The JWT header looks like this:

```json
{
  "alg": "RS256",
  "typ": "JWT",
  "kid": "Ld2tfCjn73R6spC8A0ZEn2w5KJ9JtQti5AcZtvPMDmY"
}
```

and the JWT payload looks like this:

```json
{
  "jti": "3b7a8f19-38aa-46dd-8af8-9825529f1cf7",
  "exp": 1510319182,
  "nbf": 0,
  "iat": 1510318882,
  "iss": "https://SNIP",
  "aud": "SNIP",
  "sub": "SNIP",
  "typ": "Bearer",
  "azp": "manual-test-client",
  "auth_time": 0,
  "session_state": "ef69df24-986c-4025-a60c-6460b95b3819",
  "acr": "1",
  "allowed-origins": [],
  "realm_access": {
    "roles": [
      "uma_authorization"
    ]
  },
  "resource_access": {
    "account": {
      "roles": [
        "manage-account",
        "manage-account-links",
        "view-profile"
      ]
    }
  },
  "clientId": "manual-test-client",
  "clientHost": "10.128.0.6",
  "preferred_username": "service-account-SNIP",
  "clientAddress": "10.128.0.6",
  "email": "service-account-SNIP"
}
```

The payload contains more fields than the ESP needs - should that cause an error?

Could the `nbf` being set to 0 cause an issue?

**Comment by tazjin** [comment] 2017-11-10 15:47
I've tried some more debugging by changing values in the JWT manually (hoping to proceed to a time or signature error).

This is in fact caused by `nbf = 0`, which should be a valid value (epoch 0 is *most definitely* in the past!)

**Comment by qiwzhang** [comment] 2017-11-10 17:22
@liminw @lizan Since ESP is using gRPC library for JWT checking.  This could be an issue in the gRPC code.   Could you confirm it?

**Comment by liminw** [comment] 2017-11-10 18:37
The check is indeed in gRPC. @tazjin has done a great job debugging to find out the cause. 

This is expected behavior. That is, the claims, "exp", "iat", "nbf", if provided, must contain valid values, which is the number of seconds since Epoch.

**Comment by qiwzhang** [comment] 2017-11-10 19:15
nbf = 0 is not supported.   @tazjin should I close the issue?

**Comment by tazjin** [comment] 2017-11-10 21:58
@qiwzhang That is up to you. We will be able to find an alternative to using Endpoints, but you may want to consider documenting this.

It's unclear from @liminw's response what the chosen "cutoff time" for `nbf` values is - can they not be in the past at all? Can they be 1 hour, 1 week ago? 10 years ago?

Whatever you chose, this discrepancy from the spec (which [does not](https://tools.ietf.org/html/rfc7519#section-4.1.5) constrain the set of valid values) should be documented [on this page](https://cloud.google.com/endpoints/docs/openapi/troubleshoot-jwt-openapi).

**Comment by qiwzhang** [comment] 2017-11-10 22:17
Thanks. @tazjin We will use this to update our doc.    Hi @liminw Could you help to fix this?

**Comment by lizan** [comment] 2017-11-10 22:46
I feel the nbf = 0 should pass the check. @tazjin is the JWT signed by
services yourself or some common 3rd party issuer?

**Comment by tazjin** [comment] 2017-11-10 22:59
@lizan The JWT is signed by our Keycloak instance.

**Comment by liminw** [comment] 2017-11-11 01:22
If I read it correctly, from [grpc code](https://github.com/grpc/grpc/blob/a5ddf26c3386031b2485784199160d107b972991/src/core/lib/security/credentials/jwt/jwt_verifier.cc#L268), it seems that 0 is considered the error code returned from validate_time_field().

**Comment by liminw** [comment] 2017-11-11 01:27
We will document it [on this page](https://cloud.google.com/endpoints/docs/openapi/troubleshoot-jwt-openapi) that the values for "iat", "nbf", "exp" must be numbers that are greater than 0.

**Comment by lizan** [comment] 2017-11-11 03:26
Thanks @tazjin , how easy to configure Keycloak to omit nbf or have certain nbf != 0?

@liminw yes the code reading is correct, but I don't think it is intentional, is it?

**Comment by liminw** [comment] 2017-11-14 23:32
The documentation [here](https://cloud.google.com/endpoints/docs/openapi/troubleshoot-jwt-openapi) is fixed to say that "iat", "nbf", "exp" must be numbers greater than 0.

**Closed** 2017-11-14 23:37 UTC

**Comment by naturalbeau** [comment] 2019-01-18 21:08
I also experienced the same issue when try to use keycloak as third party authentication server. So what is the solution to fix this problem? @tazjin

**Comment by tazjin** [comment] 2019-01-19 13:02
@naturalbeau We ended up writing our own authentication service, which has been humming along fine for over a year now - Keycloak is nice if your use-case falls exactly into what it supports, otherwise bending it to do what you want is a task in itself :)
