### ISSUE TITLE
After a few seconds of idle time, the next request to ESP has high latency

### ISSUE THREAD

**Issue by MrMage** [cloudendpoints/esp#385] opened 2018-04-26 06:30 UTC
I am using ESP with Cloud Endpoints connected to a gRPC backend deployed on Kubernetes engine. The proxy is configured with a working SSL certificate from Let's Encrypt.

To support Stackdriver uptime monitoring via HTTPS, I have set up an endpoints forwarding rule like this (should be irrelevant, though; I can reproduce this with direct gRPC calls as well):

    http:
      rules:
      - selector: my.service.Name.HealthCheck
        get: /HealthCheck

The gRPC handler for that method is literally a no-op — it simply returns an empty message.

However, in Cloud Endpoints, these uptime checks show up as having a very high backend latency:

<img width="1311" alt="screen shot 2018-04-26 at 08 21 18" src="https://user-images.githubusercontent.com/117466/39289069-e3c138a6-492a-11e8-932d-c47b5899abd1.png">

The first part of the screenshot consists only of those uptime checks. As you can see, the requests have a median "backend latency" of ~1s and the 95th percentile is ~2s.

I can reproduce this behavior on the command line:

    # For testing, this request goes directly to my backend. (Exposed for testing purposes through port 80. The binary info is because the gRPC protocol has some binary data; the important part is the low latency.)
    $ date; time /usr/local/opt/curl/bin/curl --http2 --data "" "http://my.domain/my.service.Name/HealthCheck"; date
    Thu Apr 26 08:15:58 CEST 2018
    Warning: Binary output can mess up your terminal. Use "--output -" to tell 
    Warning: curl to output it to your terminal anyway, or consider "--output 
    Warning: <FILE>" to save to a file.
    
    real	0m0.046s
    user	0m0.004s
    sys	0m0.003s
    Thu Apr 26 08:15:58 CEST 2018
    # Still low latency.
    $ date; time /usr/local/opt/curl/bin/curl --http2 --data "" "http://my.domain/my.service.Name/HealthCheck"; date
    Thu Apr 26 08:16:42 CEST 2018
    Warning: Binary output can mess up your terminal. Use "--output -" to tell 
    Warning: curl to output it to your terminal anyway, or consider "--output 
    Warning: <FILE>" to save to a file.
    
    real	0m0.063s
    user	0m0.004s
    sys	0m0.003s
    Thu Apr 26 08:16:42 CEST 2018
    # This request goes to the proxy. Notice the higher latency.
    $ date; time /usr/local/opt/curl/bin/curl --http2 --data "" "https://my.domain/my.service.Name/HealthCheck"; date
    Thu Apr 26 08:16:49 CEST 2018
    {}
    real	0m1.361s
    user	0m0.012s
    sys	0m0.003s
    Thu Apr 26 08:16:50 CEST 2018
    # Another slow request to the proxy.
    $ date; time /usr/local/opt/curl/bin/curl --http2 --data "" "https://my.domain/my.service.Name/HealthCheck"; date
    Thu Apr 26 08:17:04 CEST 2018
    {}
    real	0m1.134s
    user	0m0.012s
    sys	0m0.004s
    Thu Apr 26 08:17:05 CEST 2018
    # From now on, requests are much faster.
    $ date; time /usr/local/opt/curl/bin/curl --http2 --data "" "https://my.domain/my.service.Name/HealthCheck"; date
    Thu Apr 26 08:17:06 CEST 2018
    {}
    real	0m0.238s
    user	0m0.012s
    sys	0m0.003s
    Thu Apr 26 08:17:07 CEST 2018
    $ date; time /usr/local/opt/curl/bin/curl --http2 --data "" "https://my.domain/my.service.Name/HealthCheck"; date
    Thu Apr 26 08:17:09 CEST 2018
    {}
    real	0m0.143s
    user	0m0.012s
    sys	0m0.003s
    Thu Apr 26 08:17:09 CEST 2018
    $ date; time /usr/local/opt/curl/bin/curl --http2 --data "" "https://my.domain/my.service.Name/HealthCheck"; date
    Thu Apr 26 08:17:10 CEST 2018
    {}
    real	0m0.084s
    user	0m0.012s
    sys	0m0.004s
    Thu Apr 26 08:17:10 CEST 2018
    # By the way, requests to /healthz have low latency:
    $ date; time /usr/local/opt/curl/bin/curl --http2 --data "" "https://my.domain/healthz"; date
    Thu Apr 26 08:17:10 CEST 2018
    {}
    real	0m0.084s
    user	0m0.012s
    sys	0m0.004s
    Thu Apr 26 08:17:10 CEST 2018

As you can see, the first request has high latency, with much lower latency on subsequent requests. However, after a few seconds of inactivity, latency increases back to the original (high) values again.

Did anyone encounter this before or have ideas for a possible fix/workaround? Happy to provide any other logs you might need. (The default Cloud Endpoints logs just show the request, with high latency, but no extra info.)

This is my proxy's command line:

            "--ssl_port=9000",
            "--service=myservicename.myprojectid.cloud.goog",
            "--rollout_strategy=managed",
            "--backend=grpc://127.0.0.1:5050",
            "--healthz=healthz"

And this is how the proxy and backend are exposed by Kubernetes:

      - name: grpc
        port: 443
        targetPort: 9000
        protocol: TCP
      - name: grpc-backend
        port: 80
        targetPort: 5050
        protocol: TCP

**Comment by qiwzhang** [comment] 2018-04-26 17:02
@lizan could you help?

**Comment by lizan** [comment] 2018-04-26 20:12
I believe this is because ESP call Service Control and caches it for a second, so after idle, ESP will call Service Control again. Not sure why "backend latency" are shown that high though.

@qiwzhang Is there anyway to disable Service Control call for a specific path?

**Comment by MrMage** [comment] 2018-04-26 20:30
FYI it feels like the increased delay starts re-occurring after a few seconds — more than one second, but definitely less than five minutes.

**Comment by qiwzhang** [comment] 2018-04-26 23:12
@lizan is it possible that the gRPC channel (tcp connection) from ESP to the backend got reset after a few seconds.   Not sure what is the default idle reset timeout for gRPC connection?

**Comment by MrMage** [comment] 2018-04-27 05:02
FYI, I am using the SwiftGRPC library for dealing with gRPC. That library is still a bit immature, but does call into gRPC-Core for all the heavy lifting. Also happy to do/enable any debug logging to help with that?

**Comment by MrMage** [comment] 2018-04-27 09:26
I have tried this now several times with the following command

    date; time curl -v --data "" --http2 --header "X-Cloud-Trace-Context: $(openssl rand -hex 16)/0;o=1" https://my.domain/my.service.Name/HealthCheck; date

The curl verbose output correctly shows:

    > X-Cloud-Trace-Context: ddfeb160b6aa2bc48e8550a5dfaad51b/0;o=1

However, I don't see any traces whatsoever in the trace dashboard; not for this one and not for previous ones even though I have sent several thousand requests to the endpoint over the past week. The Stackdriver Trace API shows up as enabled, but also shows as not having received any requests at all over the past week. I've also just tried adding the "Cloud Trace > Agent" role manually to my service account (which already had the role "Editor"), to no avail. Any ideas?

**Comment by mangchiandjjoe** [comment] 2018-04-27 23:54
Hello Daniel, I have tried to reproduce the high latency problem on my account, but no luck to do it.

Some of my tests are:

$ date && time curl --silent http://35.224.19.68/shelves?api_key=<my_api_key> -o /dev/null 
Fri Apr 27 16:41:17 PDT 2018

real    0m0.208s
user    0m0.008s
sys     0m0.008s
$ date && time curl --silent http://35.224.19.68/shelves?api_key=<my_api_key> -o /dev/null 
Fri Apr 27 16:41:17 PDT 2018

real    0m0.209s
user    0m0.004s
sys     0m0.008s
$ date && time curl --silent http://35.224.19.68/shelves?api_key=<my_api_key> -o /dev/null 
Fri Apr 27 16:41:17 PDT 2018
^[[A
real    0m0.209s
user    0m0.004s
sys     0m0.008s
$ date && time curl --silent http://35.224.19.68/shelves?api_key=<my_api_key> -o /dev/null 
Fri Apr 27 16:41:18 PDT 2018
^[[A

real    0m0.204s
user    0m0.008s
sys     0m0.004s
$ date && time curl --silent http://35.224.19.68/shelves?api_key=<my_api_key> -o /dev/null 
Fri Apr 27 16:41:18 PDT 2018

real    0m0.203s
user    0m0.004s
sys     0m0.004s
$ date && time curl --silent http://35.224.19.68/shelves?api_key=<my_api_key> -o /dev/null 
Fri Apr 27 16:41:24 PDT 2018

real    0m0.205s
user    0m0.004s
sys     0m0.004s
$ date && time curl --silent http://35.224.19.68/shelves?api_key=<my_api_key> -o /dev/null 
Fri Apr 27 16:41:34 PDT 2018

real    0m0.206s
user    0m0.004s
sys     0m0.008s


And I can see the trace timeline in the STACKDRIVE > Trace > Trace list page.

![image](https://user-images.githubusercontent.com/1411263/39389211-25b346b2-4a3b-11e8-90a6-ab85434778ba.png)

And this is the API I enabled for my test project.

![image](https://user-images.githubusercontent.com/1411263/39389239-5a5b5d46-4a3b-11e8-9feb-52e20134d7e1.png)

Could you please enable stackdriver APIs  which are not enabled and try it again?

If you still can not see the trace timeline, please let me know.

**Comment by mangchiandjjoe** [comment] 2018-04-28 00:04
In my test environment, latencies of ServiceControl APIs are stable.
It took from 10ms to 60ms when the response is not cached and less than 1ms for cached response.

**Comment by MrMage** [comment] 2018-05-02 08:01
Hi Jae,

Thanks for trying this. Stackdriver Trace API is already enabled, but doesn't receive any request (see the very bottom of the second screenshot):

<img width="1747" alt="screen shot 2018-05-02 at 09 59 48" src="https://user-images.githubusercontent.com/117466/39512016-b5fb8556-4def-11e8-8ab2-915c8f6ac990.png">
<img width="1730" alt="screen shot 2018-05-02 at 09 59 58" src="https://user-images.githubusercontent.com/117466/39512023-b8550df4-4def-11e8-84fa-18b20002cad0.png">

Is there anything else I can try? Could this be related to my API being gRPC and not regular HTTP/REST?

Thanks,
Daniel

**Comment by qiwzhang** [comment] 2018-05-02 16:36
Cloud trace should work for gRPC too.  Could you show your cloud console "STACKDRIVE > Trace > Overview" page?

**Comment by MrMage** [comment] 2018-05-02 16:46
I'm on the go right now, but I can assure you it's completely empty. Not a single trace. Which is unsurprising given that the API seems to have never been called.

**Comment by qiwzhang** [comment] 2018-05-02 16:47
BTW,  are you using service_account key?   Are you using "-k"  or "--service_account_key" flag when deploying ESP.

https://github.com/cloudendpoints/endpoints-tools/blob/master/start_esp/start_esp.py#L415

If so, it is possible that your service account  may not have permission to talk to Stack Driver.

**Comment by MrMage** [comment] 2018-05-02 16:55
I'm not using that key — I think ESP uses my default GCE (or GKE) service account credentials provided by the environment. Do those have Stackdriver access by default?

**Comment by MrMage** [comment] 2018-05-02 17:04
Update: I had already added the "Trace Agent" role to the GCE service account and now added "Logs Writer" as well. Is that sufficient or should I add more roles, or use a dedicated service account instead?

**Comment by qiwzhang** [comment] 2018-05-02 17:10
If you don't use "-k" flag,  ESP is using the access token from GKE metadata server which is generating the access token from the default service account.  

Could you check ESP logs  by "kubectl logs" on ESP container?

I am wondering if I can see this error log:

https://github.com/cloudendpoints/esp/blob/master/src/api_manager/cloud_trace/cloud_trace.cc#L159

**Comment by qiwzhang** [comment] 2018-05-02 17:31
Yes,  I believe so.  All our tests are using the default service account.  It works.

**Comment by MrMage** [comment] 2018-05-02 18:03
Damn. Anything else I can try, eg. enable extra logs?

**Comment by mangchiandjjoe** [comment] 2018-05-03 02:06
I am sorry for the late response. My test was also using gRPC. 

To enable debug log, you need to use the custom nginx config file.

You can download the your current nginx configuration file from your pod.
```
 kubectl cp <POD>:/etc/nginx/endpoints/nginx.conf nginx.conf -n <NAMESPACE>
```

Then change the log level to debug.
```
error_log stderr debug;
```

You can use the modified nginx.conf for the endpoint runtime pod.

Please find more information the link below.

https://cloud.google.com/endpoints/docs/openapi/kubernetes-concept

Please share us the debug log for us to get more information.

**Comment by MrMage** [comment] 2018-05-03 18:41
It looks like the service account token is created with insufficient scopes:

    E  2018/05/03 18:31:36[debug]43#43: Not sending request to CloudTrace: no traces or project_id is empty.
    E  2018/05/03 18:31:37[debug]43#43: Request method SET TO: POST
    E  2018/05/03 18:31:37[debug]43#43: Metadata already available. Fetch skipped.
    E  2018/05/03 18:31:37[debug]43#43: Auth not required.
    E  2018/05/03 18:31:37[info]43#43: Skipping Firebase Rules checks since it is disabled.
    E  2018/05/03 18:31:37 [debug] 43#43: *196 GrpcBackendHandler: Handling request
    E  2018/05/03 18:31:37 [debug] 43#43: *196 GrpcGetBackendAddress: using override address "127.0.0.1:5050"
    E  2018/05/03 18:31:37 [debug] 43#43: *196 GrpcGetStub: connecting to backend=127.0.0.1:5050
    E  2018/05/03 18:31:37[debug]43#43: Not sending request to CloudTrace: no traces or project_id is empty.
    I  Server received request to 127.0.0.1:5050 calling /***/RegisterUser from ipv4:127.0.0.1:50720 with host:***.com:443
    I  x-cloud-trace-context:80469b21d19002d8ad430c970d866f5e/749268691404044340;o=1
    I  user-agent:grpc-c++/1.4.2 grpc-c/4.0.0 (linux; chttp2; gregarious)
    I  10.156.0.2 - - [03/May/2018:18:31:38 +0000] "POST /***/RegisterUser HTTP/2.0" 200 0 "-" "grpc-node/1.10.1 grpc-c/6.0.0-pre1 (osx; chttp2; glamorous)"
    E  2018/05/03 18:31:38[debug]43#43: Request method SET TO: POST
    E  2018/05/03 18:31:38[debug]43#43: Sending request to Cloud Trace.
    E  2018/05/03 18:31:38[debug]43#43: {"traces":[{"projectId":"timing-201711","traceId":"80469b21d19002d8ad430c970d866f5e","spans":[{"spanId":"14946681223369663086","kind":"RPC_SERVER","name":"***.timing.endpoints.timing-201711.cloud.goog/***.RegisterUser","startTime":"2018-05-03T18:31:37.343786581Z","endTime":"2018-05-03T18:31:38.893197235Z","labels":{"trace.cloud.google.com/agent":"esp/1.16.0"}},{"spanId":"11667147981701570623","kind":"RPC_SERVER","name":"CheckServiceControl","startTime":"2018-05-03T18:31:37.343812090Z","endTime":"2018-05-03T18:31:37.343832748Z","parentSpanId":"14946681223369663086","labels":{"000":"Service control check is not needed"}},{"spanId":"10990143615183872780","kind":"RPC_SERVER","name":"QuotaControl","startTime":"2018-05-03T18:31:37.343818970Z","endTime":"2018-05-03T18:31:37.343829956Z","parentSpanId":"14946681223369663086","labels":{"000":"Quota control check is not needed"}},{"spanId":"749268691404044340","kind":"RPC_SERVER","name":"Backend","startTime":"2018-05-03T18:31:37.343824279Z","endTime":"2018-05-03T18:31:38.892986755Z","parentSpanId":"14946681223369663086"}]}]}
    E  2018/05/03 18:31:39[debug]43#43: Trace Response: FORBIDDEN: server response status code: 403
    E  {
    E    "error": {
    E      "code": 403,
    E      "message": "Request had insufficient authentication scopes.",
    E      "status": "PERMISSION_DENIED"
    E    }
    E  }
    E  

Other than that, I can only find a `INFO:Fetching an access token from the metadata service` message related to this.

Is it possible that I need to tell the metadata service to include the Cloud Trace scope when fetching a token?

**Comment by MrMage** [comment] 2018-05-03 18:51
BTW this is one of the traces in a slightly prettier format:

    {"traces":[{"projectId":"***-201711"
    "traceId":"80469b21d19002d8ad430c970d866f5e"
    "spans":[{"spanId":"14946681223369663086"
    "kind":"RPC_SERVER"
    "name":"***.***.endpoints.***.cloud.goog/***.RegisterUser"
    "startTime":"2018-05-03T18:31:37.343786581Z"
    "endTime":"2018-05-03T18:31:38.893197235Z"
    "labels":{"trace.cloud.google.com/agent":"esp/1.16.0"}}
    {"spanId":"11667147981701570623"
    "kind":"RPC_SERVER"
    "name":"CheckServiceControl"
    "startTime":"2018-05-03T18:31:37.343812090Z"
    "endTime":"2018-05-03T18:31:37.343832748Z"
    "parentSpanId":"14946681223369663086"
    "labels":{"000":"Service control check is not needed"}}
    {"spanId":"10990143615183872780"
    "kind":"RPC_SERVER"
    "name":"QuotaControl"
    "startTime":"2018-05-03T18:31:37.343818970Z"
    "endTime":"2018-05-03T18:31:37.343829956Z"
    "parentSpanId":"14946681223369663086"
    "labels":{"000":"Quota control check is not needed"}}
    {"spanId":"749268691404044340"
    "kind":"RPC_SERVER"
    "name":"Backend"
    "startTime":"2018-05-03T18:31:37.343824279Z"
    "endTime":"2018-05-03T18:31:38.892986755Z"
    "parentSpanId":"14946681223369663086"}]}]}

From that, it looks like the backend latency is high. But again, direct requests are super fast.

**Comment by MrMage** [comment] 2018-05-03 19:18
Okay, I was able to manually create a service account that could send traces. Still surprising that it didn't work with the default service account, though.

Here are two trace screenshots; the first is slow and the second, subsequent one, fast:

<img width="1739" alt="screen shot 2018-05-03 at 21 16 36" src="https://user-images.githubusercontent.com/117466/39597996-74bf7006-4f17-11e8-8bf1-9aaa4d2aa495.png">
<img width="1748" alt="screen shot 2018-05-03 at 21 16 43" src="https://user-images.githubusercontent.com/117466/39598000-766d4202-4f17-11e8-9b83-f08f52665fc9.png">

**Comment by qiwzhang** [comment] 2018-05-03 21:03
I will close this issue then.

**Closed by qiwzhang** 2018-05-03 21:03 UTC

**Comment by rishabhj401** [comment] 2020-07-16 21:29
Hi @MrMage ,
I am also trying to use ESP with Cloud Endpoints connected to a gRPC backend deployed on Kubernetes engine along with Istio service-mesh. In my case, I'm wanting this traffic flow ( --> istio-proxy(envoy) --> ESP --> gRPC based Java backend service) but here the challenge is **I'm not getting any traffic logs on Cloud Endpoint. Also not getting data in response.**

I checked the error.log of ESP and it seems that request is routed to ESP but not getting any entry in access.log file.

Can you please assist me in this scenario.

**Comment by qiwzhang** [comment] 2020-07-16 21:45
@rishabhj401 if you can provide your detail project/service info to me privately?  I can create a support case for you.

**Comment by rishabhj401** [comment] 2020-07-17 07:24
@qiwzhang I shared the info on your email. Please check it.
